INSERT INTO `autovermietung` (`Fahrzeuge`, `Lieferanten`, `Zweigstellen`) VALUES (`FahrzeugID`,`Acura`,`Alfa Romeo`,`Aston Martin`,`Audi`,`Bently`,`BMW`,`BMW i`,`Bugatti`,`Buick`,`Byton`,`Cadillac`,`Chevrolet`,`Chrysler`,`Citroen`,`Dacia`,`Daihatsu`,`Dodge`,`DS Automobiles`,`Faraday Future`,`Ferrari`,`Fiat`,`Fisker`,`Ford`,`GMC`,`Holden`,`Honda`,`Hyundai`,`Infiniti`,`Isuzu`,`Jaguar`,`Jeep`,`Kia`,`Koenigsegg`,`Lada`,`Lamborghini`,`Lancia`,`Land Rover`,`Lexus`,`Ligier`,`Lincoln`,`Lotus`,`Mahindra`,`Maserati`,`Maybach`,`Mazda`,`Mercedes Benz`,`Mini`,`Mitsubishi`,`Morgan`,`Nissan`,`Opel`,`Pagani`,`Peugeot`,`PG`,`Piaggio`,`Porsche`,`Renault`,`Rolls Royce`,`Saab`,`Seat`,`Skoda`,`Smart`,`SsangYong`,`StreetScooter`,`Subaru`,`Suzuki`,`Tesla`,`Toyota`,`Triumph`,`TVR`,`Vauxhall`,`Volvo`,`VW`,`Wiesmann`, '2', '3');

# Import
import sqlite3

# Erstellt die Hauptdatenbank
datenbank = sqlite3.connect('Autovermietung.db')

# Mauszeiger holen
c = datenbank.cursor()

## In die Datenbank schreiben
# Fahrzeuge
c.execute("""CREATE TABLE `Fahrzeuge` (
  `FahrzeugID` int(50) NOT NULL,
  `Acura` text NOT NULL,
  `Alfa Romeo` text NOT NULL,
  `Aston Martin` text NOT NULL,
  `Audi` text NOT NULL,
  `Bently` text NOT NULL,
  `BMW` text NOT NULL,
  `BMW i` text NOT NULL,
  `Bugatti` text NOT NULL,
  `Buick` text NOT NULL,
  `Byton` text NOT NULL,
  `Cadillac` text NOT NULL,
  `Chevrolet` text NOT NULL,
  `Chrysler` text NOT NULL,
  `Citroen` text NOT NULL,
  `Dacia` text NOT NULL,
  `Daihatsu` text NOT NULL,
  `Dodge` text NOT NULL,
  `DS Automobiles` text NOT NULL,
  `Faraday Future` text NOT NULL,
  `Ferrari` text NOT NULL,
  `Fiat` text NOT NULL,
  `Fisker` text NOT NULL,
  `Ford` text NOT NULL,
  `GMC` text NOT NULL,
  `Holden` text NOT NULL,
  `Honda` text NOT NULL,
  `Hyundai` text NOT NULL,
  `Infiniti` text NOT NULL,
  `Isuzu` text NOT NULL,
  `Jaguar` text NOT NULL,
  `Jeep` text NOT NULL,
  `Kia` text NOT NULL,
  `Koenigsegg` text NOT NULL,
  `Lada` text NOT NULL,
  `Lamborghini` text NOT NULL,
  `Lancia` text NOT NULL,
  `Land Rover` text NOT NULL,
  `Lexus` text NOT NULL,
  `Ligier` text NOT NULL,
  `Lincoln` text NOT NULL,
  `Lotus` text NOT NULL,
  `Mahindra` text NOT NULL,
  `Maserati` text NOT NULL,
  `Maybach` text NOT NULL,
  `Mazda` text NOT NULL,
  `Mercedes Benz` text NOT NULL,
  `Mini` text NOT NULL,
  `Mitsubishi` text NOT NULL,
  `Morgan` text NOT NULL,
  `Nissan` text NOT NULL,
  `Opel` text NOT NULL,
  `Pagani` text NOT NULL,
  `Peugeot` text NOT NULL,
  `PG` text NOT NULL,
  `Piaggio` text NOT NULL,
  `Porsche` text NOT NULL,
  `Renault` text NOT NULL,
  `Rolls Royce` text NOT NULL,
  `Saab` text NOT NULL,
  `Seat` text NOT NULL,
  `Skoda` text NOT NULL,
  `Smart` text NOT NULL,
  `SsangYong` text NOT NULL,
  `StreetScooter` text NOT NULL,
  `Subaru` text NOT NULL,
  `Suzuki` text NOT NULL,
  `Tesla` text NOT NULL,
  `Toyota` text NOT NULL,
  `Triumph` text NOT NULL,
  `TVR` text NOT NULL,
  `Vauxhall` text NOT NULL,
  `Volvo` text NOT NULL,
  `VW` text NOT NULL,
  `Wiesmann` text NOT NULL
)""")

# Kunden
c.execute("""CREATE TABLE `Kunden` (
  `kundennummer` int(50) NOT NULL,
  `vorname` text NOT NULL,
  `nachname` text NOT NULL,
  `strasse` text NOT NULL,
  `hausnummer` int(50) NOT NULL,
  `plz` int(50) NOT NULL,
  `ort` text NOT NULL,
  `land` text NOT NULL
)""")

# Lieferanten
c.execute("""CREATE TABLE `Lieferanten` (
  `Lieferanten ID` int(50) NOT NULL,
  `Bosch` text NOT NULL,
  `Continental` text NOT NULL,
  `Denso` text NOT NULL,
  `Magna` text NOT NULL,
  `ZF Friedrichshafen` text NOT NULL,
  `Aisin` text NOT NULL,
  `Hyundai Mobis` text NOT NULL,
  `Bridgestone-Firestone` text NOT NULL,
  `Michelin` text NOT NULL,
  `Valeo` text NOT NULL,
  `Lear` text NOT NULL,
  `Faurecia` text NOT NULL,
  `Cummins` text NOT NULL,
  `Adient` text NOT NULL,
  `Goodyear` text NOT NULL,
  `Sumitomo Electric` text NOT NULL,
  `Yazaki` text NOT NULL,
  `Mahle` text NOT NULL,
  `Aptiv` text NOT NULL,
  `Weichai Power` text NOT NULL,
  `Panasonic` text NOT NULL,
  `Toyota Boshoku` text NOT NULL,
  `Schaeffler` text NOT NULL,
  `Tenneco` text NOT NULL,
  `BorgWarner` text NOT NULL,
  `Gestamp` text NOT NULL,
  `ThyssenKrupp Automotive` text NOT NULL,
  `Yanfeng Automotive Interiors` text NOT NULL,
  `Hitachi` text NOT NULL,
  `Calsonic Kansei` text NOT NULL,
  `JTEKT` text NOT NULL,
  `Autoliv` text NOT NULL,
  `GKN` text NOT NULL,
  `Beijing Hainachuan Automotive Parts` text NOT NULL,
  `Plastic Omnium` text NOT NULL,
  `Johnson Controls` text NOT NULL,
  `TE Connectivity` text NOT NULL,
  `Joyson Electronics` text NOT NULL,
  `Flex-N-Gate` text NOT NULL,
  `Dana` text NOT NULL,
  `Hella GmbH & Co.KGaA` text NOT NULL,
  `Federal-Mogul` text NOT NULL,
  `Brose` text NOT NULL,
  `Toyoda Gosei` text NOT NULL,
  `Koito Manufacturing` text NOT NULL,
  `American Axle` text NOT NULL,
  `Benteler` text NOT NULL,
  `Samvardhana Motherson` text NOT NULL,
  `Sumitomo Rubber Industries` text NOT NULL,
  `NSK Group` text NOT NULL,
  `Mitsubishi Electric` text NOT NULL,
  `Pirelli` text NOT NULL,
  `Harman` text NOT NULL,
  `Grupo Antolin` text NOT NULL,
  `Magneti Marelli` text NOT NULL,
  `NTN` text NOT NULL,
  `Hyundai WIA` text NOT NULL,
  `Hankook Tire` text NOT NULL,
  `Eberspächer` text NOT NULL,
  `Alps Electric` text NOT NULL,
  `Delphi Technologies` text NOT NULL,
  `Dräxlmaier` text NOT NULL,
  `Freudenberg` text NOT NULL,
  `Hanon Systems` text NOT NULL,
  `Nemak` text NOT NULL,
  `Leoni` text NOT NULL,
  `Tokai Rika` text NOT NULL,
  `Mando` text NOT NULL,
  `IAC` text NOT NULL,
  `Meritor` text NOT NULL,
  `Contemporary Amperex Technology (CATL)` text NOT NULL,
  `Linamar` text NOT NULL,
  `CITIC Dicastal` text NOT NULL,
  `Yokohama Rubber` text NOT NULL,
  `NHK Spring` text NOT NULL,
  `Mann+Hummel` text NOT NULL,
  `TI Automotive` text NOT NULL,
  `NXP Semiconductors` text NOT NULL,
  `Webasto` text NOT NULL,
  `Nexteer Automotive` text NOT NULL,
  `Infineon` text NOT NULL,
  `Saint-Gobain` text NOT NULL,
  `Wabco` text NOT NULL,
  `Eaton` text NOT NULL,
  `TS Tech` text NOT NULL,
  `Stanley Electric` text NOT NULL,
  `Futaba Industrial` text NOT NULL,
  `Sumitomo Riko` text NOT NULL,
  `Cooper Standard` text NOT NULL,
  `Knorr-Bremse` text NOT NULL,
  `RenesasAsahi Glass` text NOT NULL,
  `Toyo Tire & Rubber` text NOT NULL,
  `Mitsuba Corp.` text NOT NULL,
  `CIE Automotive` text NOT NULL,
  `LG Electronics` text NOT NULL,
  `Hutchinson` text NOT NULL,
  `Garrett Motion Inc.` text NOT NULL,
  `Rheinmetall Automotive` text NOT NULL,
  `Illinois Tool Works` text NOT NULL
)""")

# Rechnungen
c.execute("""CREATE TABLE `Rechnungen` (
  `Datum` date NOT NULL,
  `Kundennummer` int(50) NOT NULL,
  `Rechnungsnummer` int(50) NOT NULL,
  `Rechnungssumme` int(50) NOT NULL
)""")

# Zweigstellen
c.execute("""CREATE TABLE `Zweigstellen` (
  `ort` text NOT NULL
)""")

# Konten
c.execute("""CREATE TABLE `Konten` (
  `Kundennummer` int(50) NOT NULL,
  `IBAN` int(50) NOT NULL,
  `BIC` int(50) NOT NULL
)""")

# Mitarbeiter
c.execute("""CREATE TABLE `Mitarbeiter` (
  `MitarbeiterNr` int(50) NOT NULL,
  `Zweigstelle` text NOT NULL,
  `Vorname` text NOT NULL,
  `Nachname` text NOT NULL,
  `strasse` text NOT NULL,
  `hausnummer` int(50) NOT NULL,
  `plz` int(50) NOT NULL,
  `ort` text NOT NULL,
  `land` text NOT NULL
)""")
