def mitarbeiter_anlegen():
    print("Bitte geben Sie den Nachnamen des neuen Mitarbeiters ein:")
    user_input_m_nachname = input()
    liste_mitarbeiter=[]
    liste_mitarbeiter.insert(0,user_input_m_nachname)
    print ("Bitte geben sie den Vornamen des Mitarbeiters ein:")
    user_input_m_vorname = input()
    liste_mitarbeiter.insert(1,user_input_m_vorname)
    print ("Bitte geben sie die Strasse des neuen Mitarbeiters ein:")
    user_input_m_strasse = input()
    liste_mitarbeiter.insert(2,user_input_m_strasse)
    print ("Bitte geben sie die Hausnummer des neuen Mitarbeiters ein:")
    user_input_m_hausnummer = input()
    liste_mitarbeiter.insert(3,user_input_m_hausnummer)
    print ("Bitte geben sie die Postleitzahl des neuen Mitarbeiters ein:")
    liste_mitarbeiter_plz=[]
    user_input_m_postleitzahl = input()
    liste_mitarbeiter_plz.insert(0,user_input_m_postleitzahl)
    liste_ma_vergleich =[]
    liste_ma_vergleich.insert(0,user_input_m_postleitzahl)
    print ("Bitte geben sie den Wohnort des neuen Mitarbeiters ein:")
    user_input_m_wohnort = input()
    liste_mitarbeiter_plz.insert(1,user_input_m_wohnort)
    print ("Bitte geben sie die Telefonnummer des neuen Mitarbeiter ein:")
    user_input_m_telefonnummer = input()
    print("Danke für ihre Eingabe")
    liste_mitarbeiter.insert(4,user_input_m_telefonnummer)
    liste_mitarbeiter.append( liste_ma_vergleich[0] )
    tupel_mitarbeiter = tuple(liste_mitarbeiter)
    tupel_mitarbeiter_plz = tuple(liste_mitarbeiter_plz)
    cursor.execute("""INSERT INTO plz_id (plz, ort) VALUES (?,?)""", (tupel_mitarbeiter_plz))
    cursor.execute("""INSERT INTO mitarbeiter (nachname, vorname, strasse, hausnummer, telefonnr, plz_id) VALUES (?,?,?,?,?, (SELECT plz_id FROM plz_id WHERE plz = ? limit 1))""", tupel_mitarbeiter) #Quelle: Sven Piehl
    connection.commit()
    abfrage_taetigkeit()